FROM pytorch/pytorch

RUN apt-get update && apt-get install -y \
    git

RUN pip install \
    pylint \
    autopep8 \
    tqdm \
    tensorboard \
    jupyter \
    matplotlib \
    seaborn \
    pandas \
    packagify \
    scipy